<?php
fwrite($file, "<?php\n");
fwrite($file, "/**\n");
fwrite($file, " * File generated with MySimpleOLM v$msolm_version\n");
fwrite($file, " *\n");
fwrite($file, " * You should not modify this file.\n");
fwrite($file, " * If you need to add or modify some functionalities offered by this file,\n");
fwrite($file, " * you should see and modify the child class corresponding to this file.\n");
fwrite($file, " */\n");
fwrite($file, "\n");
fwrite($file, "namespace $nsp"."core;\n");
fwrite($file, "\n");
fwrite($file, "use \\$nsp"."$classname;\n");
fwrite($file, "use \\$nsp"."exceptions\\$manager_classname"."Exception;\n");
fwrite($file, "\n");
fwrite($file, "/**\n");
fwrite($file, " * @class $manager_core_classname : a class for managing $classname objects.\n");
fwrite($file, " * Like all other CoreManager classes, the class is a singleton an should not be instanciate.\n");
fwrite($file, " * The right way to deal with this class is to call the getInstance method on the subclass $core_classname.\n");
fwrite($file, " * Ex :\n");
fwrite($file, " * \$manager = $manager_classname::getInstance();\n");
fwrite($file, " * \$objects = \$manager->getList();\n");
fwrite($file, " * ...\n");
fwrite($file, " */\n");
fwrite($file, "class $manager_core_classname {\n");
fwrite($file, "	\n");
fwrite($file, "	// Class attributes for object management\n");
fwrite($file, "	protected static \$instance;\n");
fwrite($file, "	protected \$ldap;\n");
fwrite($file, "	protected static \$base;\n");
fwrite($file, "	protected static \$filter;\n");
fwrite($file, "	protected static \$ldapAttributesList;\n");
fwrite($file, "	protected static \$attributesMapping;\n");
fwrite($file, "	protected static \$singleAttributesIndex;\n");
fwrite($file, "	protected static \$multiAttributesIndex;\n");
fwrite($file, "	protected static \$requiredAttributesList;\n");
fwrite($file, "\n");
fwrite($file, "	/**\n");
fwrite($file, "	 * Constructor\n");
fwrite($file, "	 * This constructor should not be used.\n");
fwrite($file, "	 * Use getInstance method instead.\n");
fwrite($file, "	 * @see getInstance()\n");
fwrite($file, "	 */\n");
fwrite($file, "	protected function __construct(){\n");
fwrite($file, "		\$this->ldap = LdapConnectionProvider::getInstance();\n");
fwrite($file, "\n");
fwrite($file, "		include(__DIR__.\"/$classname.conf.php\");\n");
fwrite($file, "		self::\$base = \$ldap_base;\n");
fwrite($file, "		self::\$filter = \$ldap_filter;\n");
fwrite($file, "		self::\$ldapAttributesList = array_values(\$ldap_attributes_mapping);\n");
fwrite($file, "		self::\$attributesMapping = \$ldap_attributes_mapping;\n");
$rdn = $datas['rdn'];
$rdn_infos = $datas['attributes'][$rdn];
fwrite($file, "		self::\$singleAttributesIndex = array(strtolower(\$ldap_attributes_mapping['$rdn']) => \"$rdn\");\n");
foreach($datas['attributes'] as $attribute => $infos){
if(($attribute != $rdn) && (($infos['type'] == "value") || ($infos['type'] == "refValue")) && (! $infos['multi'])){
fwrite($file, "		if(isset(\$ldap_attributes_mapping['$attribute']) && \$ldap_attributes_mapping['$attribute'] != \"\"){\n");
fwrite($file, "			self::\$singleAttributesIndex[strtolower(\$ldap_attributes_mapping['$attribute'])] = \"$attribute\";\n");
fwrite($file, "		}\n");
}
}
fwrite($file, "		self::\$multiAttributesIndex = array();\n");
foreach($datas['attributes'] as $attribute => $infos){
if((($infos['type'] == "value") || ($infos['type'] == "refValue")) && $infos['multi']){
fwrite($file, "		if(isset(\$ldap_attributes_mapping['".$infos['attribute_pf_name']."']) && \$ldap_attributes_mapping['".$infos['attribute_pf_name']."'] != \"\"){\n");
fwrite($file, "			self::\$multiAttributesIndex[strtolower(\$ldap_attributes_mapping['".$infos['attribute_pf_name']."'])] = \"".$infos['attribute_pf_name']."\";\n");
fwrite($file, "		}\n");
}
}
fwrite($file, "		self::\$requiredAttributesList = array(");
$first = true;
foreach($datas['attributes'] as $attribute => $infos){
if(($infos['type'] == 'value') && $infos['required']){
if(! $first){
fwrite($file, ",");
}
if($infos['multi']){
fwrite($file, "\"".$infos['attribute_pf_name']."\"");
}
else{
fwrite($file, "\"$attribute\"");
}
$first = false;
}
}
fwrite($file, ");\n");
fwrite($file, "	}\n");
fwrite($file, "\n");
fwrite($file, "	/**\n");
fwrite($file, "	 * Use this method to get the instance of the manager\n");
fwrite($file, "	 * @return \\$nsp"."$manager_classname\n");
fwrite($file, "	 */\n");
fwrite($file, "	public static function getInstance(){\n");
fwrite($file, "		if(! isset(static::\$instance)) {\n");
fwrite($file, "			static::\$instance = new static;\n");
fwrite($file, "		}\n");
fwrite($file, "		return static::\$instance;\n");
fwrite($file, "	}\n");
fwrite($file, "\n");
fwrite($file, "	public function getBase(){\n");
fwrite($file, "		return self::\$base;\n");
fwrite($file, "	}\n");
fwrite($file, "\n");
fwrite($file, "	public function getRdnAttribute(){\n");
fwrite($file, "		return self::\$attributesMapping['$rdn'];\n");
fwrite($file, "	}\n");
fwrite($file, "\n");
fwrite($file, "	/**\n");
fwrite($file, "	 * Use this method to get a $classname extracted from ldap\n");
fwrite($file, "	 * @param \$id the object identifier (rdn)\n");
fwrite($file, "	 * @return \\$nsp"."$classname\n");
fwrite($file, "	 */\n");
fwrite($file, "	public function get(\$id){\n");
fwrite($file, "		try{\n");
fwrite($file, "			return \$this->getBy".$this->camelize($rdn)."(\$id);\n");
fwrite($file, "		}\n");
fwrite($file, "		catch(\\Exception \$e){\n");
fwrite($file, "			throw new ".$manager_classname."Exception(\$e->getMessage(), 2, \$e);\n");
fwrite($file, "		}\n");
fwrite($file, "	}\n");
fwrite($file, "\n");
fwrite($file, "	/**\n");
fwrite($file, "	 * Use this method to check if a $classname exists in the ldap.\n");
fwrite($file, "	 * Using this method is faster than get method then check if value is returned.\n");
fwrite($file, "	 * @param \$id the object identifier (rdn)\n");
fwrite($file, "	 * @return boolean true if a corresponding entry is found, false otherwise\n");
fwrite($file, "	 */\n");
fwrite($file, "	public function exists(\$id){\n");
fwrite($file, "		try{\n");
fwrite($file, "			return \$this->existsBy".$this->camelize($rdn)."(\$id);\n");
fwrite($file, "		}\n");
fwrite($file, "		catch(\\Exception \$e){\n");
fwrite($file, "			throw new ".$manager_classname."Exception(\$e->getMessage(), 2, \$e);\n");
fwrite($file, "		}\n");
fwrite($file, "	}\n");
fwrite($file, "\n");
foreach($datas['attributes'] as $attribute => $infos){
if((($infos['type'] == 'value') || ($infos['type'] == "refValue")) && ($infos['unique'] || $infos['rdn'])){
fwrite($file, "	/**\n");
fwrite($file, "	 * getBy".$this->camelize($attribute)." method\n");
fwrite($file, "	 * @param \$value a value of $attribute (defined as unique or rdn)\n");
fwrite($file, "	 * @return \\$nsp"."$classname object\n");
fwrite($file, "	 */\n");
fwrite($file, "	public function getBy".$this->camelize($attribute)."(\$value){\n");
fwrite($file, "		if(! (isset(self::\$attributesMapping['$attribute']) && self::\$attributesMapping['$attribute'] != \"\")){\n");
fwrite($file, "			throw new ".$manager_classname."Exception(\"No ldap attribute mapping defined for \$attribute. Could not proceed\");\n");
fwrite($file, "		}\n");
fwrite($file, "		try{\n");
fwrite($file, "			\$datas = \$this->ldap->search(\"(&(\".self::\$attributesMapping['$attribute'].\"=\$value)\".self::\$filter.\")\", self::\$ldapAttributesList, self::\$base);\n");
fwrite($file, "			if(\$datas){\n");
fwrite($file, "				if(\$datas['count'] > 1){\n");
fwrite($file, "					throw new ".$manager_classname."Exception(\"Multiple entries found for $attribute=\$value while attribute is defined as unique\");\n");
fwrite($file, "				}\n");
fwrite($file, "				\$cdatas = array();\n");
fwrite($file, "				foreach(\$datas[0] as \$key => \$values){\n");
fwrite($file, "					if(isset(self::\$singleAttributesIndex[\$key])){\n");
fwrite($file, "						\$cdatas[self::\$singleAttributesIndex[\$key]] = \$values[0];\n");
fwrite($file, "					}\n");
fwrite($file, "					elseif(isset(self::\$multiAttributesIndex[\$key])){\n");
fwrite($file, "						\$cdatas[self::\$multiAttributesIndex[\$key]] = array();\n");
fwrite($file, "						for(\$i=0; \$i < \$values['count']; \$i++){\n");
fwrite($file, "							\$cdatas[self::\$multiAttributesIndex[\$key]][] = \$values[\$i];\n");
fwrite($file, "						}\n");
fwrite($file, "					}\n");
fwrite($file, "				}\n");
fwrite($file, "				\$cdatas['dn'] = \$datas[0]['dn'];\n");
fwrite($file, "				return new $classname(\$cdatas);\n");
fwrite($file, "			}\n");
fwrite($file, "			return null;\n");
fwrite($file, "		}\n");
fwrite($file, "		catch(\\Exception \$e){\n");
fwrite($file, "			throw new ".$manager_classname."Exception(\$e->getMessage(), 2, \$e);\n");
fwrite($file, "		}\n");
fwrite($file, "	}\n");
fwrite($file, "\n");
fwrite($file, "	/**\n");
fwrite($file, "	 * existsBy".$this->camelize($attribute)." method\n");
fwrite($file, "	 * Using this method is faster than using corresponding get method then check if a value is returned.\n");
fwrite($file, "	 * @param \$value a value of $attribute (defined as unique or primary key)\n");
fwrite($file, "	 * @return boolean true if a corresponding entry is found, false otherwise\n");
fwrite($file, "	 */\n");
fwrite($file, "	public function existsBy".$this->camelize($attribute)."(\$value){\n");
fwrite($file, "		if(! (isset(self::\$attributesMapping['$attribute']) && self::\$attributesMapping['$attribute'] != \"\")){\n");
fwrite($file, "			throw new ".$manager_classname."Exception(\"No ldap attribute mapping defined for \$attribute. Could not proceed\");\n");
fwrite($file, "		}\n");
fwrite($file, "		try{\n");
fwrite($file, "			\$datas = \$this->ldap->search(\"(&(\".self::\$attributesMapping['$attribute'].\"=\$value)\".self::\$filter.\")\", self::\$ldapAttributesList, self::\$base);\n");
fwrite($file, "			if(\$datas){\n");
fwrite($file, "				if(\$datas['count'] > 1){\n");
fwrite($file, "					throw new ".$manager_classname."Exception(\"Multiple entries found for $attribute=\$value while attribute is defined as unique\");\n");
fwrite($file, "				}\n");
fwrite($file, "				return true;\n");
fwrite($file, "			}\n");
fwrite($file, "			return false;\n");
fwrite($file, "		}\n");
fwrite($file, "		catch(\\Exception \$e){\n");
fwrite($file, "			throw new ".$manager_classname."Exception(\$e->getMessage(), 2, \$e);\n");
fwrite($file, "		}\n");
fwrite($file, "	}\n");
fwrite($file, "\n");
}
}
fwrite($file, "	/**\n");
fwrite($file, "	 * Inserts a new object in the ldap directory.\n");
fwrite($file, "	 * Related objects are added or modified according the object attributes\n");
fwrite($file, "	 * @param \$object a $classname object\n");
fwrite($file, "	 * @param \$cascade this parameter should not be used. It exists for internal purpose only.\n");
fwrite($file, "	 * @return ".$rdn_infos['datatype']['type']." object identifier (rdn)\n");
fwrite($file, "	 */\n");
fwrite($file, "	public function add($classname \$object){\n");
fwrite($file, "		if(! \$object->_isNew()){\n");
fwrite($file, "			throw new ".$manager_classname."Exception('This object is extracted from ldap or has already been save. Perhaps you should use update method instead', 1);\n");
fwrite($file, "		}\n");
fwrite($file, "		if(\$object->_isDeleted()){\n");
fwrite($file, "			throw new ".$manager_classname."Exception('This object has been deleted. You cannot add it again', 1);\n");
fwrite($file, "		}\n");
fwrite($file, "\n");
fwrite($file, "		try{\n");
fwrite($file, "			\$datas = \$object->getDatas();\n");
fwrite($file, "			\$ldap_datas = array();\n");
fwrite($file, "			foreach(\$datas as \$key => \$value){\n");
fwrite($file, "				if((is_array(\$value) && empty(\$value)) || (\$value == null || \$value == \"\")){\n");
fwrite($file, "					unset(\$datas[\$key]);\n");
fwrite($file, "				}\n");
fwrite($file, "				else{\n");
fwrite($file, "					if(isset(self::\$attributesMapping[\$key]) && self::\$attributesMapping[\$key] != \"\"){\n");
fwrite($file, "						\$ldap_datas[self::\$attributesMapping[\$key]] = \$value;\n");
fwrite($file, "					}\n");
fwrite($file, "				}\n");
fwrite($file, "			}\n");
fwrite($file, "			\$this->ldap->add(\$object->getDn(), \$ldap_datas);\n");
fwrite($file, "			\$oid = \$object->get".$this->camelize($rdn)."();\n");
fwrite($file, "			\$object->_setNew(false);\n");
fwrite($file, "		}\n");
fwrite($file, "		catch(\\Exception \$e){\n");
fwrite($file, "			throw new ".$manager_classname."Exception(\$e->getMessage(), 2, \$e);\n");
fwrite($file, "		}\n");
fwrite($file, "		return \$oid;\n");
fwrite($file, "	}\n");
fwrite($file, "\n");
fwrite($file, "	/**\n");
fwrite($file, "	 * Updates an existing object in ldap according the modifications done on it.\n");
fwrite($file, "	 * Related objects are added or modified according the object attributes.\n");
fwrite($file, "	 * @param \$object a $classname object\n");
fwrite($file, "	 * @param \$cascade this parameter should not be used. It exists for internal purpose only.\n");
fwrite($file, "	 */\n");
fwrite($file, "	public function update($classname \$object){\n");
fwrite($file, "		if(\$object->_isNew()){\n");
fwrite($file, "			throw new ".$manager_classname."Exception('This object is a new object. Perhaps you should use add method instead', 1);\n");
fwrite($file, "		}\n");
fwrite($file, "		if(\$object->_isDeleted()){\n");
fwrite($file, "			throw new ".$manager_classname."Exception('This object has been deleted. You cannot update it', 1);\n");
fwrite($file, "		}\n");
fwrite($file, "\n");
fwrite($file, "		if(\$object->_isModified()){\n");
fwrite($file, "			try{\n");
fwrite($file, "				if(\$object->_isRenamed()){\n");
fwrite($file, "					\$this->ldap->rename(\$object->getOriginalDn(), \$object->getDn());\n");
fwrite($file, "				}\n");
fwrite($file, "				\$datas = \$object->getDatas();\n");
fwrite($file, "				// Active Directory does not accept the rdn is part of the attributes passed to modify method even if is equal to the original rdn\n");
fwrite($file, "				unset(\$datas['$rdn']);\n");
fwrite($file, "				// Idem but faster than : foreach(\$datas as \$key => \$data){ if(\$data == null)	\$datas[\$key] = array(); }\n");
fwrite($file, "				\$datas = array_replace(\$datas, array_fill_keys(array_keys(\$datas, null), array()));\n");
fwrite($file, "				\$ldap_datas = array();\n");
fwrite($file, "				foreach(\$datas as \$key => \$value){\n");
fwrite($file, "					if(isset(self::\$attributesMapping[\$key]) && self::\$attributesMapping[\$key] != \"\"){\n");
fwrite($file, "						\$ldap_datas[self::\$attributesMapping[\$key]] = \$value;\n");
fwrite($file, "					}\n");
fwrite($file, "				}\n");
fwrite($file, "				// Active Directory never give the password so the unicodePwd will always be empty unless it was set\n");
fwrite($file, "				// So if it's null it doesn't mean we have to delete it\n");
fwrite($file, "				if(isset(\$ldap_datas['unicodePwd']) && empty(\$ldap_datas['unicodePwd'])){\n");
fwrite($file, "					unset(\$ldap_datas['unicodePwd']);\n");
fwrite($file, "				}\n");
fwrite($file, "				\$this->ldap->modify(\$object->getDn(), \$ldap_datas);\n");
fwrite($file, "			}\n");
fwrite($file, "			catch(\\Exception \$e){\n");
fwrite($file, "				throw new ".$manager_classname."Exception(\$e->getMessage(), 2, \$e);\n");
fwrite($file, "			}\n");
fwrite($file, "			\$object->_setModified(false);\n");
fwrite($file, "		}\n");
fwrite($file, "	}\n");
fwrite($file, "\n");
fwrite($file, "	/**\n");
fwrite($file, "	 * Deletes an existing object in ldap.\n");
fwrite($file, "	 * Related objects are modified according this deletion, but are not deleted.\n");
fwrite($file, "	 * @param \$object a $classname object\n");
fwrite($file, "	 * @param \$cascade this parameter should not be used. It exists for internal purpose only.\n");
fwrite($file, "	 */\n");
fwrite($file, "	public function delete($classname \$object){\n");
fwrite($file, "		if(\$object->_isNew()){\n");
fwrite($file, "			throw new ".$manager_classname."Exception('This object is a new object. Cannot delete it', 1);\n");
fwrite($file, "		}\n");
fwrite($file, "		if(\$object->_isDeleted()){\n");
fwrite($file, "			throw new ".$manager_classname."Exception('This object has already been deleted. You cannot delete it again', 1);\n");
fwrite($file, "		}\n");
fwrite($file, "\n");
fwrite($file, "		try{\n");
fwrite($file, "			\$this->ldap->delete(\$object->getDn());\n");
fwrite($file, "		}\n");
fwrite($file, "		catch(\\Exception \$e){\n");
fwrite($file, "			throw new ".$manager_classname."Exception(\$e->getMessage(), 2, \$e);\n");
fwrite($file, "		}\n");
fwrite($file, "\n");
fwrite($file, "		\$object->_setDeleted(true);\n");
fwrite($file, "	}\n");
fwrite($file, "\n");
fwrite($file, "	/**\n");
fwrite($file, "	 * Get the number of objects in ldap.\n");
fwrite($file, "	 * @return integer - the number of $classname objects.\n");
fwrite($file, "	 */\n");
fwrite($file, "	public function count(){\n");
fwrite($file, "		try{\n");
fwrite($file, "			\$datas = \$this->ldap->search(self::\$filter, array(), self::\$base);\n");
fwrite($file, "			if(\$datas){\n");
fwrite($file, "				return \$datas['count'];\n");
fwrite($file, "			}\n");
fwrite($file, "			return 0;\n");
fwrite($file, "		}\n");
fwrite($file, "		catch(\\Exception \$e){\n");
fwrite($file, "			throw new ".$manager_classname."Exception(\$e->getMessage(), 2, \$e);\n");
fwrite($file, "		}\n");
fwrite($file, "	}\n");
fwrite($file, "\n");
fwrite($file, "	/**\n");
fwrite($file, "	 * Get a set of existing objects in the  ldap directory.\n");
fwrite($file, "	 * @param \$sortAttributes (optional) could be a single string or an array of string corresponding to the columns names where datas are stored. Could be null. Default null.\n");
fwrite($file, "	 * @param \$asArray (optional) boolean : if true the return is a 2 dimensions array containing datas in the corresponding entries ($classname). Default false.\n");
fwrite($file, "	 * @return \\$nsp"."$classname"."[] - an array of $classname : the objects found in storage according \$offset and \$limit parameters passed. If \$asArray is set to true, returns a 2 dimensions array containing datas of these objects.\n");
fwrite($file, "	 */\n");
fwrite($file, "	public function getList(\$sortAttributes = null, \$asArray = false){\n");
fwrite($file, "		\$objects = array();\n");
fwrite($file, "\n");
fwrite($file, "		try{\n");
fwrite($file, "			\$datas = \$this->ldap->search(self::\$filter, self::\$ldapAttributesList, self::\$base, \$sortAttributes);\n");
fwrite($file, "			if(\$datas){\n");
fwrite($file, "				unset(\$datas['count']);\n");
fwrite($file, "				if(\$asArray){\n");
fwrite($file, "					foreach(\$datas as \$i => \$entry){\n");
fwrite($file, "						\$cdatas = array();\n");
fwrite($file, "						foreach(\$entry as \$key => \$values){\n");
fwrite($file, "							if(isset(self::\$singleAttributesIndex[\$key])){\n");
fwrite($file, "								\$cdatas[self::\$singleAttributesIndex[\$key]] = \$values[0];\n");
fwrite($file, "							}\n");
fwrite($file, "							elseif(isset(self::\$multiAttributesIndex[\$key])){\n");
fwrite($file, "								\$cdatas[self::\$multiAttributesIndex[\$key]] = array();\n");
fwrite($file, "								for(\$i=0; \$i < \$values['count']; \$i++){\n");
fwrite($file, "									\$cdatas[self::\$multiAttributesIndex[\$key]][] = \$values[\$i];\n");
fwrite($file, "								}\n");
fwrite($file, "							}\n");
fwrite($file, "						}\n");
fwrite($file, "						\$cdatas['dn'] = \$datas[0]['dn'];\n");
fwrite($file, "						\$objects[] = \$cdatas;\n");
fwrite($file, "					}\n");
fwrite($file, "				}\n");
fwrite($file, "				else{\n");
fwrite($file, "					foreach(\$datas as \$i => \$entry){\n");
fwrite($file, "						\$cdatas = array();\n");
fwrite($file, "						foreach(\$entry as \$key => \$values){\n");
fwrite($file, "							if(isset(self::\$singleAttributesIndex[\$key])){\n");
fwrite($file, "								\$cdatas[self::\$singleAttributesIndex[\$key]] = \$values[0];\n");
fwrite($file, "							}\n");
fwrite($file, "							elseif(isset(self::\$multiAttributesIndex[\$key])){\n");
fwrite($file, "								\$cdatas[self::\$multiAttributesIndex[\$key]] = array();\n");
fwrite($file, "								for(\$i=0; \$i < \$values['count']; \$i++){\n");
fwrite($file, "									\$cdatas[self::\$multiAttributesIndex[\$key]][] = \$values[\$i];\n");
fwrite($file, "								}\n");
fwrite($file, "							}\n");
fwrite($file, "						}\n");
fwrite($file, "						\$cdatas['dn'] = \$datas[0]['dn'];\n");
fwrite($file, "						\$objects[] = new $classname(\$cdatas);\n");
fwrite($file, "					}\n");
fwrite($file, "					\n");
fwrite($file, "				}\n");
fwrite($file, "				return \$objects;\n");
fwrite($file, "			}\n");
fwrite($file, "			return null;\n");
fwrite($file, "		}\n");
fwrite($file, "		catch(\\Exception \$e){\n");
fwrite($file, "			throw new ".$manager_classname."Exception(\$e->getMessage(), 2, \$e);\n");
fwrite($file, "		}\n");
fwrite($file, "	}\n");
fwrite($file, "	/**\n");
fwrite($file, "	 * Get a set of existing objects in the  ldap directory according a filter.\n");
fwrite($file, "	 * @param \$filter a filter to select only some entries among the entries defined by the object class\n");
fwrite($file, "	 * @param \$sortAttributes (optional) could be a single string or an array of string corresponding to the columns names where datas are stored. Could be null. Default null.\n");
fwrite($file, "	 * @param \$asArray (optional) boolean : if true the return is a 2 dimensions array containing datas in the corresponding entries ($classname). Default false.\n");
fwrite($file, "	 * @return \\$nsp"."$classname"."[] - an array of $classname : the objects found in storage according \$offset and \$limit parameters passed. If \$asArray is set to true, returns a 2 dimensions array containing datas of these objects.\n");
fwrite($file, "	 */\n");
fwrite($file, "	public function getFilteredList(\$filter, \$sortAttributes = null, \$asArray = false){\n");
fwrite($file, "		\$objects = array();\n");
fwrite($file, "\n");
fwrite($file, "		try{\n");
fwrite($file, "			\$datas = \$this->ldap->search(\"(&\$filter\".self::\$filter.\")\", self::\$ldapAttributesList, self::\$base, \$sortAttributes);\n");
fwrite($file, "			if(\$datas){\n");
fwrite($file, "				unset(\$datas['count']);\n");
fwrite($file, "				if(\$asArray){\n");
fwrite($file, "					foreach(\$datas as \$i => \$entry){\n");
fwrite($file, "						\$cdatas = array();\n");
fwrite($file, "						foreach(\$entry as \$key => \$values){\n");
fwrite($file, "							if(isset(self::\$singleAttributesIndex[\$key])){\n");
fwrite($file, "								\$cdatas[self::\$singleAttributesIndex[\$key]] = \$values[0];\n");
fwrite($file, "							}\n");
fwrite($file, "							elseif(isset(self::\$multiAttributesIndex[\$key])){\n");
fwrite($file, "								\$cdatas[self::\$multiAttributesIndex[\$key]] = array();\n");
fwrite($file, "								for(\$i=0; \$i < \$values['count']; \$i++){\n");
fwrite($file, "									\$cdatas[self::\$multiAttributesIndex[\$key]][] = \$values[\$i];\n");
fwrite($file, "								}\n");
fwrite($file, "							}\n");
fwrite($file, "						}\n");
fwrite($file, "						\$cdatas['dn'] = \$datas[0]['dn'];\n");
fwrite($file, "						\$objects[] = \$cdatas;\n");
fwrite($file, "					}\n");
fwrite($file, "				}\n");
fwrite($file, "				else{\n");
fwrite($file, "					foreach(\$datas as \$i => \$entry){\n");
fwrite($file, "						\$cdatas = array();\n");
fwrite($file, "						foreach(\$entry as \$key => \$values){\n");
fwrite($file, "							if(isset(self::\$singleAttributesIndex[\$key])){\n");
fwrite($file, "								\$cdatas[self::\$singleAttributesIndex[\$key]] = \$values[0];\n");
fwrite($file, "							}\n");
fwrite($file, "							elseif(isset(self::\$multiAttributesIndex[\$key])){\n");
fwrite($file, "								\$cdatas[self::\$multiAttributesIndex[\$key]] = array();\n");
fwrite($file, "								for(\$i=0; \$i < \$values['count']; \$i++){\n");
fwrite($file, "									\$cdatas[self::\$multiAttributesIndex[\$key]][] = \$values[\$i];\n");
fwrite($file, "								}\n");
fwrite($file, "							}\n");
fwrite($file, "						}\n");
fwrite($file, "						\$cdatas['dn'] = \$datas[0]['dn'];\n");
fwrite($file, "						\$objects[] = new $classname(\$cdatas);\n");
fwrite($file, "					}\n");
fwrite($file, "					\n");
fwrite($file, "				}\n");
fwrite($file, "				return \$objects;\n");
fwrite($file, "			}\n");
fwrite($file, "			return null;\n");
fwrite($file, "		}\n");
fwrite($file, "		catch(\\Exception \$e){\n");
fwrite($file, "			throw new ".$manager_classname."Exception(\$e->getMessage(), 2, \$e);\n");
fwrite($file, "		}\n");
fwrite($file, "	}\n");
fwrite($file, "}\n");
fwrite($file, "?>");
?>